// @generated by vendor/build.mjs. Do not edit.

//! Every file in the plugin asset bundle, as `(logical path, bytes)`.
//!
//! Lazy locale and hyphenation chunks compile in only with their Cargo
//! feature.

/// The bundle file list. `vendor/build.mjs` writes it.
pub(crate) static FILES: &[(&str, &[u8])] = &[
    (
        "autumn-univer.css",
        include_bytes!("../assets/autumn-univer.css"),
    ),
    ("init.js", include_bytes!("../assets/init.js")),
    (
        "THIRD-PARTY-LICENSES.txt",
        include_bytes!("../assets/dist/THIRD-PARTY-LICENSES.txt"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/af-DK_CjRn6-ZTA5VVNH.js",
        include_bytes!("../assets/dist/chunks/af-DK_CjRn6-ZTA5VVNH.js"),
    ),
    #[cfg(feature = "locale-ar-sa")]
    (
        "chunks/ar-SA-TOXA6TJW.js",
        include_bytes!("../assets/dist/chunks/ar-SA-TOXA6TJW.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/as-BPtSu6VN-RBOQULEH.js",
        include_bytes!("../assets/dist/chunks/as-BPtSu6VN-RBOQULEH.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/be-CrQ0smca-5M4ELRLU.js",
        include_bytes!("../assets/dist/chunks/be-CrQ0smca-5M4ELRLU.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/bg-CrQqGwni-6DJL5RRM.js",
        include_bytes!("../assets/dist/chunks/bg-CrQqGwni-6DJL5RRM.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/bn-NCLZcWHi-HIVMLX6I.js",
        include_bytes!("../assets/dist/chunks/bn-NCLZcWHi-HIVMLX6I.js"),
    ),
    #[cfg(feature = "locale-ca-es")]
    (
        "chunks/ca-ES-ANNTTJCX.js",
        include_bytes!("../assets/dist/chunks/ca-ES-ANNTTJCX.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ca-SUf6Y2Om-PXRBUNOD.js",
        include_bytes!("../assets/dist/chunks/ca-SUf6Y2Om-PXRBUNOD.js"),
    ),
    #[cfg(any(feature = "locale-zh-hk", feature = "locale-zh-tw"))]
    (
        "chunks/chunk-EYSSW52Y.js",
        include_bytes!("../assets/dist/chunks/chunk-EYSSW52Y.js"),
    ),
    (
        "chunks/chunk-K32HWP5M.js",
        include_bytes!("../assets/dist/chunks/chunk-K32HWP5M.js"),
    ),
    (
        "chunks/chunk-TNYJG4JF.js",
        include_bytes!("../assets/dist/chunks/chunk-TNYJG4JF.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/cop-C3sk0IUo-DJMCVVJQ.js",
        include_bytes!("../assets/dist/chunks/cop-C3sk0IUo-DJMCVVJQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/cs-CmAteokq-B7FNRTX2.js",
        include_bytes!("../assets/dist/chunks/cs-CmAteokq-B7FNRTX2.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/cu-CBUlrW6Y-GHH64MQD.js",
        include_bytes!("../assets/dist/chunks/cu-CBUlrW6Y-GHH64MQD.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/cy-BBPa6z2x-ZABIYDXH.js",
        include_bytes!("../assets/dist/chunks/cy-BBPa6z2x-ZABIYDXH.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/da-CCDXfXtG-HSA7S5NO.js",
        include_bytes!("../assets/dist/chunks/da-CCDXfXtG-HSA7S5NO.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/de-1901-CWoAOigE-IL6TZNE3.js",
        include_bytes!("../assets/dist/chunks/de-1901-CWoAOigE-IL6TZNE3.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/de-1996-BL6awyxG-4FKGOLMK.js",
        include_bytes!("../assets/dist/chunks/de-1996-BL6awyxG-4FKGOLMK.js"),
    ),
    #[cfg(feature = "locale-de-de")]
    (
        "chunks/de-DE-OLWPC7IP.js",
        include_bytes!("../assets/dist/chunks/de-DE-OLWPC7IP.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/de-ch-1901-hVThVHVb-ZKVDFBEZ.js",
        include_bytes!("../assets/dist/chunks/de-ch-1901-hVThVHVb-ZKVDFBEZ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/el-monoton-D3aKqTz2-YSHCIEAD.js",
        include_bytes!("../assets/dist/chunks/el-monoton-D3aKqTz2-YSHCIEAD.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/el-polyton-ogVWcTzh-YUJE4LFC.js",
        include_bytes!("../assets/dist/chunks/el-polyton-ogVWcTzh-YUJE4LFC.js"),
    ),
    (
        "chunks/en-US-B75X3K5H.js",
        include_bytes!("../assets/dist/chunks/en-US-B75X3K5H.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/en-gb-B7Al27b_-V3W7TWPH.js",
        include_bytes!("../assets/dist/chunks/en-gb-B7Al27b_-V3W7TWPH.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/es-DcaaHPU_-JOSRMPHV.js",
        include_bytes!("../assets/dist/chunks/es-DcaaHPU_-JOSRMPHV.js"),
    ),
    #[cfg(feature = "locale-es-es")]
    (
        "chunks/es-ES-L6B25XNA.js",
        include_bytes!("../assets/dist/chunks/es-ES-L6B25XNA.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/et-B_spaleu-RAR7RFR2.js",
        include_bytes!("../assets/dist/chunks/et-B_spaleu-RAR7RFR2.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/eu-Ctv_kq9Z-LNAAZXCP.js",
        include_bytes!("../assets/dist/chunks/eu-Ctv_kq9Z-LNAAZXCP.js"),
    ),
    #[cfg(feature = "locale-fa-ir")]
    (
        "chunks/fa-IR-WY24BZWB.js",
        include_bytes!("../assets/dist/chunks/fa-IR-WY24BZWB.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/fi-RW5VB8Yp-WIXATD46.js",
        include_bytes!("../assets/dist/chunks/fi-RW5VB8Yp-WIXATD46.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/fr-BC2onEz9-5GNIXU3U.js",
        include_bytes!("../assets/dist/chunks/fr-BC2onEz9-5GNIXU3U.js"),
    ),
    #[cfg(feature = "locale-fr-fr")]
    (
        "chunks/fr-FR-BEZEXDAG.js",
        include_bytes!("../assets/dist/chunks/fr-FR-BEZEXDAG.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/fur-AC12wySk-ZQVSCGUM.js",
        include_bytes!("../assets/dist/chunks/fur-AC12wySk-ZQVSCGUM.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ga-Cn6LkudM-Z5QDRRZA.js",
        include_bytes!("../assets/dist/chunks/ga-Cn6LkudM-Z5QDRRZA.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/gl-DZGc-K_G-IER426TY.js",
        include_bytes!("../assets/dist/chunks/gl-DZGc-K_G-IER426TY.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/grc-DOlGgO8T-QOYY6B4F.js",
        include_bytes!("../assets/dist/chunks/grc-DOlGgO8T-QOYY6B4F.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/gu-Bjl0l-cf-PCYLCAH2.js",
        include_bytes!("../assets/dist/chunks/gu-Bjl0l-cf-PCYLCAH2.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/hi-DsAaTPCC-WC4RO54Z.js",
        include_bytes!("../assets/dist/chunks/hi-DsAaTPCC-WC4RO54Z.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/hr-DT1SBBes-EIUQN4ZW.js",
        include_bytes!("../assets/dist/chunks/hr-DT1SBBes-EIUQN4ZW.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/hsb-DC_ITc1e-5UMYCLFC.js",
        include_bytes!("../assets/dist/chunks/hsb-DC_ITc1e-5UMYCLFC.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/hu-DVk7Y_ka-6VA3WSV3.js",
        include_bytes!("../assets/dist/chunks/hu-DVk7Y_ka-6VA3WSV3.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/hy-e995ysyO-PBU55Q6F.js",
        include_bytes!("../assets/dist/chunks/hy-e995ysyO-PBU55Q6F.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ia-Cr4TJH0c-FTD3YMAA.js",
        include_bytes!("../assets/dist/chunks/ia-Cr4TJH0c-FTD3YMAA.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/id-DifDyWg9-VNOYAMUH.js",
        include_bytes!("../assets/dist/chunks/id-DifDyWg9-VNOYAMUH.js"),
    ),
    #[cfg(feature = "locale-id-id")]
    (
        "chunks/id-ID-XENHBPKX.js",
        include_bytes!("../assets/dist/chunks/id-ID-XENHBPKX.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/is-BT8UVRze-IMNXCZR4.js",
        include_bytes!("../assets/dist/chunks/is-BT8UVRze-IMNXCZR4.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/it-Bt_Meacx-AWTCLFII.js",
        include_bytes!("../assets/dist/chunks/it-Bt_Meacx-AWTCLFII.js"),
    ),
    #[cfg(feature = "locale-it-it")]
    (
        "chunks/it-IT-LBDVZ5BD.js",
        include_bytes!("../assets/dist/chunks/it-IT-LBDVZ5BD.js"),
    ),
    #[cfg(feature = "locale-ja-jp")]
    (
        "chunks/ja-JP-MKUDNKHQ.js",
        include_bytes!("../assets/dist/chunks/ja-JP-MKUDNKHQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ka-jyoLzyDE-ALEIEU2E.js",
        include_bytes!("../assets/dist/chunks/ka-jyoLzyDE-ALEIEU2E.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/kmr-Cfwhwuff-K6OSYBCH.js",
        include_bytes!("../assets/dist/chunks/kmr-Cfwhwuff-K6OSYBCH.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/kn-C6Lov-DP-67GNU33O.js",
        include_bytes!("../assets/dist/chunks/kn-C6Lov-DP-67GNU33O.js"),
    ),
    #[cfg(feature = "locale-ko-kr")]
    (
        "chunks/ko-KR-CKSXL27K.js",
        include_bytes!("../assets/dist/chunks/ko-KR-CKSXL27K.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/la-DuvHjUWw-RLAVLULQ.js",
        include_bytes!("../assets/dist/chunks/la-DuvHjUWw-RLAVLULQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/la-x-classic-yTyAOQEt-A7QKRPF6.js",
        include_bytes!("../assets/dist/chunks/la-x-classic-yTyAOQEt-A7QKRPF6.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/la-x-liturgic-CXeQb4FY-WY5CGIVM.js",
        include_bytes!("../assets/dist/chunks/la-x-liturgic-CXeQb4FY-WY5CGIVM.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/lt-BBe8DlDF-JQHGPSAP.js",
        include_bytes!("../assets/dist/chunks/lt-BBe8DlDF-JQHGPSAP.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/lv-Q2BBHnzp-AZN6ELQQ.js",
        include_bytes!("../assets/dist/chunks/lv-Q2BBHnzp-AZN6ELQQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ml-2xLVYkVY-25IBLSXQ.js",
        include_bytes!("../assets/dist/chunks/ml-2xLVYkVY-25IBLSXQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/mn-cyrl-lHM4n0oC-XVF5DC3S.js",
        include_bytes!("../assets/dist/chunks/mn-cyrl-lHM4n0oC-XVF5DC3S.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/mn-cyrl-x-lmc-3aetruI8-4HAHUE7E.js",
        include_bytes!("../assets/dist/chunks/mn-cyrl-x-lmc-3aetruI8-4HAHUE7E.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/mr-CjWJPVmH-YD7HH5M7.js",
        include_bytes!("../assets/dist/chunks/mr-CjWJPVmH-YD7HH5M7.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/mul-ethi-D_CMSMEq-K5ZFENML.js",
        include_bytes!("../assets/dist/chunks/mul-ethi-D_CMSMEq-K5ZFENML.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/nb-DI8u59ch-AQP77JSQ.js",
        include_bytes!("../assets/dist/chunks/nb-DI8u59ch-AQP77JSQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/nl-BHQJ6Gvn-NNT56D75.js",
        include_bytes!("../assets/dist/chunks/nl-BHQJ6Gvn-NNT56D75.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/nn-ntZvarUK-WDAAUQMN.js",
        include_bytes!("../assets/dist/chunks/nn-ntZvarUK-WDAAUQMN.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/no-B8ItS0F3-RBMFKZJH.js",
        include_bytes!("../assets/dist/chunks/no-B8ItS0F3-RBMFKZJH.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/oc-P_i3-xLA-2UCZGO23.js",
        include_bytes!("../assets/dist/chunks/oc-P_i3-xLA-2UCZGO23.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/or-50rxpoq4-CO5KK2CS.js",
        include_bytes!("../assets/dist/chunks/or-50rxpoq4-CO5KK2CS.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/pa-C54UG8eN-IMINWK7I.js",
        include_bytes!("../assets/dist/chunks/pa-C54UG8eN-IMINWK7I.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/pi-B9cgjyG1-YI5IQSH4.js",
        include_bytes!("../assets/dist/chunks/pi-B9cgjyG1-YI5IQSH4.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/pl-9fg-ESVt-KFOUWURL.js",
        include_bytes!("../assets/dist/chunks/pl-9fg-ESVt-KFOUWURL.js"),
    ),
    #[cfg(feature = "locale-pl-pl")]
    (
        "chunks/pl-PL-GUIN4CYJ.js",
        include_bytes!("../assets/dist/chunks/pl-PL-GUIN4CYJ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/pms-BRGfm5gS-CMBTUGEE.js",
        include_bytes!("../assets/dist/chunks/pms-BRGfm5gS-CMBTUGEE.js"),
    ),
    #[cfg(feature = "locale-pt-br")]
    (
        "chunks/pt-BR-FZDXMYMJ.js",
        include_bytes!("../assets/dist/chunks/pt-BR-FZDXMYMJ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/pt-Cum2_NUC-MXWATUON.js",
        include_bytes!("../assets/dist/chunks/pt-Cum2_NUC-MXWATUON.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/rm-C0MIK9N4-PSAEQIOW.js",
        include_bytes!("../assets/dist/chunks/rm-C0MIK9N4-PSAEQIOW.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ro-0fmdH0HA-4C477LWL.js",
        include_bytes!("../assets/dist/chunks/ro-0fmdH0HA-4C477LWL.js"),
    ),
    #[cfg(feature = "locale-ru-ru")]
    (
        "chunks/ru-RU-NWN7L5VE.js",
        include_bytes!("../assets/dist/chunks/ru-RU-NWN7L5VE.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ru-v4l-ayaq-KBMWV5VY.js",
        include_bytes!("../assets/dist/chunks/ru-v4l-ayaq-KBMWV5VY.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sa-CKY9c_Vq-WD2DEFAQ.js",
        include_bytes!("../assets/dist/chunks/sa-CKY9c_Vq-WD2DEFAQ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sh-cyrl-BpCRFOmq-4TJBSGZA.js",
        include_bytes!("../assets/dist/chunks/sh-cyrl-BpCRFOmq-4TJBSGZA.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sh-latn-sRy4Tuaj-HCV4SHLS.js",
        include_bytes!("../assets/dist/chunks/sh-latn-sRy4Tuaj-HCV4SHLS.js"),
    ),
    #[cfg(feature = "locale-sk-sk")]
    (
        "chunks/sk-SK-E25NCRXE.js",
        include_bytes!("../assets/dist/chunks/sk-SK-E25NCRXE.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sk-_iOeDNrQ-UBRVC2IB.js",
        include_bytes!("../assets/dist/chunks/sk-_iOeDNrQ-UBRVC2IB.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sl-DpiklF-D-P3SIPNNG.js",
        include_bytes!("../assets/dist/chunks/sl-DpiklF-D-P3SIPNNG.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sr-cyrl-Dpzrbd0W-M2JNNJDK.js",
        include_bytes!("../assets/dist/chunks/sr-cyrl-Dpzrbd0W-M2JNNJDK.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/sv-CFm5y56M-EEQHVWJ5.js",
        include_bytes!("../assets/dist/chunks/sv-CFm5y56M-EEQHVWJ5.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/ta-BcghgTbD-FZ5CGX6P.js",
        include_bytes!("../assets/dist/chunks/ta-BcghgTbD-FZ5CGX6P.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/te-B5Spl2Jk-3V3UFT3A.js",
        include_bytes!("../assets/dist/chunks/te-B5Spl2Jk-3V3UFT3A.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/th-DWX5iPSo-EZJAGJJL.js",
        include_bytes!("../assets/dist/chunks/th-DWX5iPSo-EZJAGJJL.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/tk-BMbKB10q-JWVSGTVN.js",
        include_bytes!("../assets/dist/chunks/tk-BMbKB10q-JWVSGTVN.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/tr-CIHIuzqc-DTLZ6KDK.js",
        include_bytes!("../assets/dist/chunks/tr-CIHIuzqc-DTLZ6KDK.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/uk-Dir3oxLs-6TO5PKYO.js",
        include_bytes!("../assets/dist/chunks/uk-Dir3oxLs-6TO5PKYO.js"),
    ),
    #[cfg(feature = "locale-vi-vn")]
    (
        "chunks/vi-VN-SUFQBBPP.js",
        include_bytes!("../assets/dist/chunks/vi-VN-SUFQBBPP.js"),
    ),
    #[cfg(feature = "locale-zh-cn")]
    (
        "chunks/zh-CN-GWUUMAIZ.js",
        include_bytes!("../assets/dist/chunks/zh-CN-GWUUMAIZ.js"),
    ),
    #[cfg(feature = "locale-zh-hk")]
    (
        "chunks/zh-HK-XAJGLKOI.js",
        include_bytes!("../assets/dist/chunks/zh-HK-XAJGLKOI.js"),
    ),
    #[cfg(feature = "locale-zh-tw")]
    (
        "chunks/zh-TW-NI7VQNNJ.js",
        include_bytes!("../assets/dist/chunks/zh-TW-NI7VQNNJ.js"),
    ),
    #[cfg(feature = "hyphenation")]
    (
        "chunks/zh-latn-pinyin-BdYb-Ey_-BBJNQD26.js",
        include_bytes!("../assets/dist/chunks/zh-latn-pinyin-BdYb-Ey_-BBJNQD26.js"),
    ),
    ("univer.css", include_bytes!("../assets/dist/univer.css")),
    ("univer.js", include_bytes!("../assets/dist/univer.js")),
];
